---
- name: Install git
  yum:
    name: git
    state: latest
- name: Download installer
  get_url:
    url: "{{ installer_url }}"
    dest: /tmp/{{ installer_url | basename }}
    mode: 0555
  register: installer
- name: Generate response file for unattended install
  template:
    src: "{{ app_name }}_response.varfile.j2"
    dest: /tmp/response.varfile
    mode: 0644
- name: Install the package
  command: "{{ installer.dest }} -q -varfile /tmp/response.varfile"
- name: Generate properties file for Tomcat
  template:
    src: "{{ app_name }}.properties.j2"
    dest: "{{ home_dir }}/shared/{{ app_name }}.properties"
    mode: 0644
    force: False